(part "LM61440AANRJRR"
    (packageRef "LM61440AASQRJRRQ1")
    (interface
        (port "1" (symbPinId 1) (portName "BIAS_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VCC") (portType INOUT))
        (port "3" (symbPinId 3) (portName "AGND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "FB") (portType INOUT))
        (port "5" (symbPinId 5) (portName "PGOOD_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EN/SYNC") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "PGND1_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SW") (portType INOUT))
        (port "11" (symbPinId 11) (portName "PGND2_1") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VIN2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "RBOOT") (portType INOUT))
        (port "14" (symbPinId 14) (portName "CBOOT") (portType INOUT))
        (port "15" (symbPinId 15) (portName "BIAS_2") (portType INOUT))
        (port "16" (symbPinId 16) (portName "PGOOD_2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "PGND1_2") (portType INOUT))
        (port "18" (symbPinId 18) (portName "PGND2_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-LM61440AANRJRR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM61440AANRJRR?qs=vmHwEFxEFR8iu%252B2xr1IAew%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM61440AANRJRR")
    (property "Description" "Switching Controllers 3-V to 36-V, 4-A, low-noise synchronous step-down converter 14-VQFN-HR -40 to 150")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/LM61440")
    (property "symbolName1" "LM61440AANRJRR")
)
